### ISSUE TITLE
Feed Forward NN in Attention

### ISSUE THREAD

**Issue by hieudx149** [yinghao1019/Joint_learn#1]
Hi, @yinghao1019 
Can you explain me why in Attentioner line 79 you init a linear layer with in_features = hidden_dim * 3, but when you pass hiddens into this layer hiddens just have size is hidden_dim * 2 (line 90) ?
![Screenshot from 2021-11-15 10-36-05](https://user-images.githubusercontent.com/61724310/141718879-7dc8741a-9dad-43cb-8c2a-173cc1a40de2.png)

**Comment by hieudx149** [comment]
decoder_hiddens here is just hidden state of 1 timestep or all timestep ?

**Comment by yinghao1019** [comment]
@r1ckC139  Beacuse encoder outputs is Bidirectional RNN,so in line 79's hid_dim is correct (hid_dim*3), line 90's comment I will fix. Thanks for your review.
